<?xml version="1.0" encoding="utf-8"?>
<Database Name="baseball" Class="BaseballDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=baseball;Integrated Security=True" SettingsObjectName="MLBImport.My.MySettings" SettingsPropertyName="baseballConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.players" Member="players">
    <Type Name="player">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(46) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BatsThrows" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(46) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Born" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Birthplace" Type="System.String" DbType="NVarChar(46) NOT NULL" CanBeNull="false" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.teams" Member="teams">
    <Type Name="team">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="shortname" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="longname" Type="System.String" DbType="NVarChar(65) NOT NULL" CanBeNull="false" />
      <Column Name="number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="manager" Type="System.String" DbType="NVarChar(65) NOT NULL" CanBeNull="false" />
      <Column Name="league" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>