'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="baseball")>  _
Partial Public Class BaseballDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Insertplayer(instance As player)
    End Sub
  Partial Private Sub Updateplayer(instance As player)
    End Sub
  Partial Private Sub Deleteplayer(instance As player)
    End Sub
  Partial Private Sub Insertteam(instance As team)
    End Sub
  Partial Private Sub Updateteam(instance As team)
    End Sub
  Partial Private Sub Deleteteam(instance As team)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.MLBXMLTest.My.MySettings.Default.baseballConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property players() As System.Data.Linq.Table(Of player)
		Get
			Return Me.GetTable(Of player)
		End Get
	End Property
	
	Public ReadOnly Property teams() As System.Data.Linq.Table(Of team)
		Get
			Return Me.GetTable(Of team)
		End Get
	End Property
End Class

<Table(Name:="dbo.players")>  _
Partial Public Class player
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _Name As String
	
	Private _Position As String
	
	Private _BatsThrows As String
	
	Private _Status As String
	
	Private _Height As String
	
	Private _Weight As Integer
	
	Private _Born As Date
	
	Private _Birthplace As String
	
	Private _TeamID As Integer
	
	Private _LastUpdate As Date
	
	Private _Number As Integer
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnPositionChanging(value As String)
    End Sub
    Partial Private Sub OnPositionChanged()
    End Sub
    Partial Private Sub OnBatsThrowsChanging(value As String)
    End Sub
    Partial Private Sub OnBatsThrowsChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As String)
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnHeightChanging(value As String)
    End Sub
    Partial Private Sub OnHeightChanged()
    End Sub
    Partial Private Sub OnWeightChanging(value As Integer)
    End Sub
    Partial Private Sub OnWeightChanged()
    End Sub
    Partial Private Sub OnBornChanging(value As Date)
    End Sub
    Partial Private Sub OnBornChanged()
    End Sub
    Partial Private Sub OnBirthplaceChanging(value As String)
    End Sub
    Partial Private Sub OnBirthplaceChanged()
    End Sub
    Partial Private Sub OnTeamIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnTeamIDChanged()
    End Sub
    Partial Private Sub OnLastUpdateChanging(value As Date)
    End Sub
    Partial Private Sub OnLastUpdateChanged()
    End Sub
    Partial Private Sub OnNumberChanging(value As Integer)
    End Sub
    Partial Private Sub OnNumberChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Column(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Name", DbType:="NVarChar(46) NOT NULL", CanBeNull:=false)>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Position", DbType:="NVarChar(3) NOT NULL", CanBeNull:=false)>  _
	Public Property Position() As String
		Get
			Return Me._Position
		End Get
		Set
			If (String.Equals(Me._Position, value) = false) Then
				Me.OnPositionChanging(value)
				Me.SendPropertyChanging
				Me._Position = value
				Me.SendPropertyChanged("Position")
				Me.OnPositionChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_BatsThrows", DbType:="NVarChar(4) NOT NULL", CanBeNull:=false)>  _
	Public Property BatsThrows() As String
		Get
			Return Me._BatsThrows
		End Get
		Set
			If (String.Equals(Me._BatsThrows, value) = false) Then
				Me.OnBatsThrowsChanging(value)
				Me.SendPropertyChanging
				Me._BatsThrows = value
				Me.SendPropertyChanged("BatsThrows")
				Me.OnBatsThrowsChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Status", DbType:="NVarChar(46) NOT NULL", CanBeNull:=false)>  _
	Public Property Status() As String
		Get
			Return Me._Status
		End Get
		Set
			If (String.Equals(Me._Status, value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Height", DbType:="NVarChar(6) NOT NULL", CanBeNull:=false)>  _
	Public Property Height() As String
		Get
			Return Me._Height
		End Get
		Set
			If (String.Equals(Me._Height, value) = false) Then
				Me.OnHeightChanging(value)
				Me.SendPropertyChanging
				Me._Height = value
				Me.SendPropertyChanged("Height")
				Me.OnHeightChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Weight", DbType:="Int NOT NULL")>  _
	Public Property Weight() As Integer
		Get
			Return Me._Weight
		End Get
		Set
			If ((Me._Weight = value)  _
						= false) Then
				Me.OnWeightChanging(value)
				Me.SendPropertyChanging
				Me._Weight = value
				Me.SendPropertyChanged("Weight")
				Me.OnWeightChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Born", DbType:="DateTime NOT NULL")>  _
	Public Property Born() As Date
		Get
			Return Me._Born
		End Get
		Set
			If ((Me._Born = value)  _
						= false) Then
				Me.OnBornChanging(value)
				Me.SendPropertyChanging
				Me._Born = value
				Me.SendPropertyChanged("Born")
				Me.OnBornChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Birthplace", DbType:="NVarChar(46) NOT NULL", CanBeNull:=false)>  _
	Public Property Birthplace() As String
		Get
			Return Me._Birthplace
		End Get
		Set
			If (String.Equals(Me._Birthplace, value) = false) Then
				Me.OnBirthplaceChanging(value)
				Me.SendPropertyChanging
				Me._Birthplace = value
				Me.SendPropertyChanged("Birthplace")
				Me.OnBirthplaceChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_TeamID", DbType:="Int NOT NULL")>  _
	Public Property TeamID() As Integer
		Get
			Return Me._TeamID
		End Get
		Set
			If ((Me._TeamID = value)  _
						= false) Then
				Me.OnTeamIDChanging(value)
				Me.SendPropertyChanging
				Me._TeamID = value
				Me.SendPropertyChanged("TeamID")
				Me.OnTeamIDChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_LastUpdate", DbType:="DateTime NOT NULL")>  _
	Public Property LastUpdate() As Date
		Get
			Return Me._LastUpdate
		End Get
		Set
			If ((Me._LastUpdate = value)  _
						= false) Then
				Me.OnLastUpdateChanging(value)
				Me.SendPropertyChanging
				Me._LastUpdate = value
				Me.SendPropertyChanged("LastUpdate")
				Me.OnLastUpdateChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_Number", DbType:="Int NOT NULL")>  _
	Public Property Number() As Integer
		Get
			Return Me._Number
		End Get
		Set
			If ((Me._Number = value)  _
						= false) Then
				Me.OnNumberChanging(value)
				Me.SendPropertyChanging
				Me._Number = value
				Me.SendPropertyChanged("Number")
				Me.OnNumberChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Table(Name:="dbo.teams")>  _
Partial Public Class team
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _id As Integer
	
	Private _shortname As String
	
	Private _longname As String
	
	Private _number As Integer
	
	Private _manager As String
	
	Private _league As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidChanging(value As Integer)
    End Sub
    Partial Private Sub OnidChanged()
    End Sub
    Partial Private Sub OnshortnameChanging(value As String)
    End Sub
    Partial Private Sub OnshortnameChanged()
    End Sub
    Partial Private Sub OnlongnameChanging(value As String)
    End Sub
    Partial Private Sub OnlongnameChanged()
    End Sub
    Partial Private Sub OnnumberChanging(value As Integer)
    End Sub
    Partial Private Sub OnnumberChanged()
    End Sub
    Partial Private Sub OnmanagerChanging(value As String)
    End Sub
    Partial Private Sub OnmanagerChanged()
    End Sub
    Partial Private Sub OnleagueChanging(value As String)
    End Sub
    Partial Private Sub OnleagueChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Column(Storage:="_id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property id() As Integer
		Get
			Return Me._id
		End Get
		Set
			If ((Me._id = value)  _
						= false) Then
				Me.OnidChanging(value)
				Me.SendPropertyChanging
				Me._id = value
				Me.SendPropertyChanged("id")
				Me.OnidChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_shortname", DbType:="NVarChar(4) NOT NULL", CanBeNull:=false)>  _
	Public Property shortname() As String
		Get
			Return Me._shortname
		End Get
		Set
			If (String.Equals(Me._shortname, value) = false) Then
				Me.OnshortnameChanging(value)
				Me.SendPropertyChanging
				Me._shortname = value
				Me.SendPropertyChanged("shortname")
				Me.OnshortnameChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_longname", DbType:="NVarChar(65) NOT NULL", CanBeNull:=false)>  _
	Public Property longname() As String
		Get
			Return Me._longname
		End Get
		Set
			If (String.Equals(Me._longname, value) = false) Then
				Me.OnlongnameChanging(value)
				Me.SendPropertyChanging
				Me._longname = value
				Me.SendPropertyChanged("longname")
				Me.OnlongnameChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_number", DbType:="Int NOT NULL")>  _
	Public Property number() As Integer
		Get
			Return Me._number
		End Get
		Set
			If ((Me._number = value)  _
						= false) Then
				Me.OnnumberChanging(value)
				Me.SendPropertyChanging
				Me._number = value
				Me.SendPropertyChanged("number")
				Me.OnnumberChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_manager", DbType:="NVarChar(65) NOT NULL", CanBeNull:=false)>  _
	Public Property manager() As String
		Get
			Return Me._manager
		End Get
		Set
			If (String.Equals(Me._manager, value) = false) Then
				Me.OnmanagerChanging(value)
				Me.SendPropertyChanging
				Me._manager = value
				Me.SendPropertyChanged("manager")
				Me.OnmanagerChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_league", DbType:="NVarChar(9) NOT NULL", CanBeNull:=false)>  _
	Public Property league() As String
		Get
			Return Me._league
		End Get
		Set
			If (String.Equals(Me._league, value) = false) Then
				Me.OnleagueChanging(value)
				Me.SendPropertyChanging
				Me._league = value
				Me.SendPropertyChanged("league")
				Me.OnleagueChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
